blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),  

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    # Example: /add/
    url(r'^add/$',
        BookmarkCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        BookmarkChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        BookmarkUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        BookmarkDeleteView.as_view(), name="delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

polls/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import root_views # 루트 인덱스

urlpatterns = [
    url(r'^$', root_views.index, name='index'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView) :
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView) :
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}


<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <div id="post-preview" style="text-align: center">

    <h1>북마크 수정 </h1>
            </div>
    <table class="change-list" style="width:100%;text-align: center; margin:0 auto;      table-layout:fixed;
    word-break:break-all;">
        <tr>
            <th>제목</th>
            <th style="width:40%">링크</th>
            <th>글쓴이</th>
            <th>수정</th>
            <th>삭제</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td style="width:40%">{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a class="btn btn-warning" href="{% url 'bookmark:update' item.id %}">수정</a></td>
            <td><a class="btn btn-warning" href="{% url 'bookmark:delete' item.id %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>
        </div>
      </div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <div id="post-preview" style="text-align: center">
    <h1>북마크 삭제</h1>

    <form action="" method="post">{% csrf_token %}
        <p>"{{ object }}" - 삭제하시겠습니까? ?</p>
        <input type="submit" class="btn btn-warning" value="확인" />
    </form>

            </div></div></div></div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <div id="post-preview" style="text-align: center">
    <h1>{{ object.title }}</h1>

    <ul style="list-style: none;">
        <li>링크: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
            </div></div></div></div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <div id="post-preview" style="text-align: center">

    <h1>북마크 수정</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">오류! 아래 에러를 수정하십시오.</p>
    {% endif %}

    <p>제목과 링크를 입력해주세요</p>
    <fieldset class="aligned" >

        <div id="post-preview"  >
           제목 :  {{ form.title }}
        </div>

        <div id="post-preview" >
            링크 : {{ form.url }}
        </div>

    </fieldset>


    <div class="submit-row">
        <input class="btn btn-warning" type="submit" value="등록"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

            </div></div></div></div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% block content %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <div id="post-preview" style="text-align: center">
    <h1>북마크 목록</h1>

    <ul style="list-style: none;">
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
            </div></div></div></div>
{% endblock %}