blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),  

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

polls/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import root_views # 루트 인덱스

urlpatterns = [
    url(r'^$', root_views.index, name='index'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>t1802pet</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "main/vendor/bootstrap/css/bootstrap.min.css"%}' rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href='{% static "main/vendor/font-awesome/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">
    <link href='{% static 'https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'%}'  rel='stylesheet' type='text/css'>
    <link href='{% static  'https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'%}'  rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href='{% static "main/css/clean-blog.min.css" %}' rel="stylesheet">
      <link href='{% static "main/css/landing-page.css" %}' rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container" >
        <a class="navbar-brand" href="{% url 'home' %}">t1802pet</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
               <a class="nav-link" href="{% url 'home' %}">홈 <span class="sr-only">(current)</span></a>
            </li> -->

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">병원가기</a>
          </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'photo:index' %}">펫기록부</a>
            </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'bookmark:index' %}">펫친구들</a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post_archive' %}">페키지소개</a>
            </li>

            <!-- <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">페키지소개</a>
            </li> -->

          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">추가</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01" role="menu">
                <a class="dropdown-item"  href="{% url 'bookmark:add' %}">북마크</a>
                <a class="dropdown-item"  href="{% url 'blog:add' %}">포스트</a>
                <a class="dropdown-item"  href="{% url 'photo:album_add' %}">앨범</a>
                <a class="dropdown-item"  href="{% url 'photo:photo_add' %}">사진</a>
            </div>
          </li>

           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">변화</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown02" role="menu">
                    <li role="presentation"><a class="dropdown-item" role="menu-item" href="{% url 'bookmark:change' %}">북마크</a></li>
                    <li><a class="dropdown-item" href="{% url 'blog:change' %}">포스트</a></li>
                    <li><a class="dropdown-item" href="{% url 'photo:album_change' %}">앨범</a></li>
                    <li><a class="dropdown-item" href="{% url 'photo:photo_change' %}">사진</a></li>
                </ul>
            </li> -->


             <li class="nav-item dropdown">
              {% if user.is_active %}
             <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">로그아웃</a>
                 {% else %}<a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">로그인</a>
                 {% endif %}
                 <ul class="dropdown-menu" aria-labelledby="dropdown02" role="menu">
                    <li>
                         {% if user.is_active %}
                             <span class="dropdown-item">{% firstof user.get_short_name user.get_username %}님</span>
                        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                        {% else %}
                             <span class="dropdown-item">방문자님</span>
                        <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                        {% endif %}
                    </li>
                    <li>
                       {% if user.is_active %}
                           <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호변경</a>
                        {% else %}
                        <a  class="dropdown-item" href="{% url 'register' %}">등록</a>
                        {% endif %}
                    </li>
                </ul>
            </li>

          </ul>

        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../static/main/img/a.jpg')">

      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading" >
              <!-- <h1> Hello! </h1> -->
                <!-- <span class="subheading">This is Django Project </span> -->
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Bootstrap core JavaScript -->
    <script src='{% static "main/vendor/jquery/jquery.min.js"%}'></script>
    <script src='{% static "main/vendor/bootstrap/js/bootstrap.bundle.min.js" %}'></script>

    <!-- Custom scripts for this template -->
    <script src="js/clean-blog.min.js"></script>
{% block content %}{% endblock %}
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; t1802pet Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

  </body>

</html>

templates/base1.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}장고 웹프로그래밍 만들기{% endblock %}</title>

{% load staticfiles %}
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Off Canvas Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">쉽고&amp;빠른 장고 웹프로그래밍</h2>
    {% if user.is_active %}
    <h4 class="welcome">환영합니다.
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">환영합니다. 방문자님 /
                <a href="{% url 'login' %}">로그인</a> /
                <a href="{% url 'register' %}">등록</a>
    </h4>
    {% endif %}
</div>

   <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-primary">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">홈 <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'bookmark:index' %}">북마크</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">블로그</a>
          </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'photo:index' %}">앨범</a>
            </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">추가</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item"  href="{% url 'bookmark:add' %}">북마크</a>
                <a class="dropdown-item"  href="{% url 'blog:add' %}">포스트</a>
                <a class="dropdown-item"  href="{% url 'photo:album_add' %}">앨범</a>
                <a class="dropdown-item"  href="{% url 'photo:photo_add' %}">사진</a>
            </div>
          </li>


            <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">변화</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'bookmark:change' %}">북마크</a>
                    <a class="dropdown-item" href="{% url 'blog:change' %}">포스트</a>
                    <a class="dropdown-item" href="{% url 'photo:album_change' %}">앨범</a>
                    <a class="dropdown-item" href="{% url 'photo:photo_change' %}">사진</a>
                </div>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post_archive' %}">포스트기록</a>
            </li>

            <li class="nav-item">
                <a  class="nav-link"href="{% url 'blog:search' %}">블로그검색</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">관리자</a>
            </li>




        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>


{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}장고 웹프로그래밍 만들기{% endblock %}</title>

{% load staticfiles %}
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Off Canvas Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">

   <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-primary">
      <div a class="navbar-brand">
    <h2 class="maintitle">쉽고&amp;빠른 장고 웹프로그래밍</h2>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
</div>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">홈 <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'bookmark:index' %}">북마크</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">블로그</a>
          </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'photo:index' %}">앨범</a>
            </li>


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">추가</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01" role="menu">
                <a class="dropdown-item"  href="{% url 'bookmark:add' %}">북마크</a>
                <a class="dropdown-item"  href="{% url 'blog:add' %}">포스트</a>
                <a class="dropdown-item"  href="{% url 'photo:album_add' %}">앨범</a>
                <a class="dropdown-item"  href="{% url 'photo:photo_add' %}">사진</a>
            </div>
          </li>

            <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">변화</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown02" role="menu">
                    <li role="presentation"><a class="dropdown-item" role="menu-item" href="{% url 'bookmark:change' %}">북마크</a></li>
                    <li><a class="dropdown-item" href="{% url 'blog:change' %}">포스트</a></li>
                    <li><a class="dropdown-item" href="{% url 'photo:album_change' %}">앨범</a></li>
                    <li><a class="dropdown-item" href="{% url 'photo:photo_change' %}">사진</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Portfolio
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
              </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post_archive' %}">포스트기록</a>
            </li>

            <li class="nav-item">
                <a  class="nav-link"href="{% url 'blog:search' %}">블로그검색</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">관리자</a>
            </li>




        </ul>
      </div>
<div a class="navbar-brand">

    {% if user.is_active %}
    <h4 class="welcome">환영합니다.
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">비밀번호변경</a>
                <a href="{% url 'logout' %}">로그아웃</a>
    </h4>
    {% else %}
    <h4 class="welcome">환영합니다. 방문자님 /
                <a href="{% url 'login' %}">로그인</a>
                <a href="{% url 'register' %}">등록</a>
    </h4>
    {% endif %}
</div>

    </nav>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}

{% block content %}

<section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">

          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('../../static/main/img/hos.jpg'); " ></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
              <a href="{% url 'blog:index' %}"><h2>병원가기</h2></a>
            <p class="lead mb-0"> 당신의 동물병원을 찾아보세요.</p>
              <p class="lead mb-0"> 예약도 가능하답니다</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('../../static/main/img/list.jpg');" ></div>
          <div class="col-lg-6 my-auto showcase-text">
              <a href="{% url 'bookmark:index' %}"><h2>펫기록부</h2></a>
            <p class="lead mb-0">
                반려동물의 진료기록을 확인해보세요. </p>
            <p class="lead mb-0">  예방접종 날짜도 확인할 수 있어요..</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('../../static/main/img/dog.jpg');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
              <a href="{% url 'photo:index' %}"><h2>펫친구들</h2></a>
            <p class="lead mb-0">
                당신의 펫을 자랑해보세요.</p>
                <p class="lead mb-0">
                    사진을 올리고 </p>
                    <p class="lead mb-0">정보를 공유해보세요</p>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}